//
// MotivesCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum MotivesCategory: String, Codable {
    case createOperation = "CREATE_OPERATION"
    case leaveOperation = "LEAVE_OPERATION"
    case cancelOperation = "CANCEL_OPERATION"
}
